// MUTATIONS TYPES

// Main

export const SET_IS_ONLINE = 'SET_IS_ONLINE'

// Ingredients

export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'
export const TOGGLE_INGREDIENT = 'TOGGLE_INGREDIENT'
export const TOGGLE_ALL_INGREDIENTS = 'TOGGLE_ALL_INGREDIENTS'

// Messages

export const FETCH_MESSAGES = 'FETCH_MESSAGES'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
export const TOGGLE_MESSAGE = 'TOGGLE_MESSAGE'
export const TOGGLE_ALL_MESSAGES = 'TOGGLE_ALL_MESSAGES'
