// MUTATIONS TYPES

// Main

export const SET_IS_ONLINE = 'SET_IS_ONLINE'

// Settings

export const SET_LANGUAGE = 'SET_LANGUAGE'
export const SET_CURRENCY = 'SET_CURRENCY'
export const SET_MODE = 'SET_MODE'
export const SET_FAVORITE = 'SET_FAVORITE'

// Ingredients

export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS'
export const ADD_INGREDIENT = 'ADD_INGREDIENT'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'
export const TOGGLE_INGREDIENT = 'TOGGLE_INGREDIENT'
export const TOGGLE_ALL_INGREDIENTS = 'TOGGLE_ALL_INGREDIENTS'
export const SET_INGREDIENT = 'SET_INGREDIENT'

// Recipes

export const SET_CURRENT_RECIPE_ID = 'SET_CURRENT_RECIPE_ID'

export const SET_RECIPE_NAME = 'SET_RECIPE_NAME'
export const SET_RECIPE_DESCRIPTION = 'SET_RECIPE_DESCRIPTION'
export const SET_RECIPE_QUANTITY = 'SET_RECIPE_QUANTITY'
export const SET_RECIPE_PGVGRATIO = 'SET_RECIPE_PGVGRATIO'
export const SET_RECIPE_NICOTINE = 'SET_RECIPE_NICOTINE'

export const ADD_RECIPE_INGREDIENT = 'ADD_RECIPE_INGREDIENT'
export const DELETE_RECIPE_INGREDIENT = 'DELETE_RECIPE_INGREDIENT'
export const SET_RECIPE_INGREDIENT_ID = 'SET_RECIPE_INGREDIENT_ID'
export const SET_RECIPE_INGREDIENT_RATIO = 'SET_RECIPE_INGREDIENT_RATIO'

export const ADD_RECIPE = 'ADD_RECIPE'
export const DELETE_RECIPE = 'DELETE_RECIPE'
export const TOGGLE_RECIPE_STAR = 'TOGGLE_RECIPE_STAR'
