// MUTATIONS TYPES

// Main

export const SET_IS_ONLINE = 'SET_IS_ONLINE'

// Settings

export const SET_LANGUAGE = 'SET_LANGUAGE'
export const SET_CURRENCY = 'SET_CURRENCY'

// Ingredients

export const FETCH_INGREDIENTS = 'FETCH_INGREDIENTS'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'
export const TOGGLE_INGREDIENT = 'TOGGLE_INGREDIENT'
export const TOGGLE_ALL_INGREDIENTS = 'TOGGLE_ALL_INGREDIENTS'

// Recipe

export const SET_RECIPE_NAME = 'SET_RECIPE_NAME'
export const SET_RECIPE_QUANTITY = 'SET_RECIPE_QUANTITY'
export const SET_RECIPE_PGVGRATIO = 'SET_RECIPE_PGVGRATIO'
export const SET_RECIPE_NICOTINE = 'SET_RECIPE_NICOTINE'

export const ADD_RECIPE_INGREDIENT = 'ADD_RECIPE_INGREDIENT'
export const DELETE_RECIPE_INGREDIENT = 'DELETE_RECIPE_INGREDIENT'
export const SET_RECIPE_INGREDIENT_ID = 'SET_RECIPE_INGREDIENT_ID'
export const SET_RECIPE_INGREDIENT_RATIO = 'SET_RECIPE_INGREDIENT_RATIO'

// Messages

export const FETCH_MESSAGES = 'FETCH_MESSAGES'
export const DELETE_MESSAGE = 'DELETE_MESSAGE'
export const TOGGLE_MESSAGE = 'TOGGLE_MESSAGE'
export const TOGGLE_ALL_MESSAGES = 'TOGGLE_ALL_MESSAGES'
